export const UsersData = [
    {
        id:1,
        name:"Aditya1",
        username:"ad1"
    },
    {
        id:2,
        name:"Aditya2",
        username:"ad2"
    },
    {
        id:3,
        name:"Aditya3",
        username:"ad3"
    },
    {
        id:4,
        name:"Aditya4",
        username:"ad4"
    },
    {
        id:5,
        name:"Aditya5",
        username:"ad5"
    },
    {
        id:6,
        name:"Aditya6",
        username:"ad6"
    },
    {
        id:7,
        name:"Aditya7",
        username:"ad7"
    },
    {
        id:8,
        name:"Aditya8",
        username:"ad8"
    },
]